resources:
  - url: http://127.0.0.1:5000/temperature-map-card.js
    type: module
views:
  - cards:
      - type: custom:temperature-map-card
        name: Temperature Map Card Development
        entity: sun.sun
        test_gui: true
